import Foundation

/// Protocol for Usage Table lookup operations
public protocol UsageTableLookupProtocol: Sendable {
    /// Look up the human-readable name for a Usage Page
    /// - Parameter page: The Usage Page ID
    /// - Returns: Human-readable page name, or hex string for unknown pages
    func lookupPageName(page: UInt16) -> String

    /// Look up the human-readable name for a Usage within a page
    /// - Parameters:
    ///   - page: The Usage Page ID
    ///   - usage: The Usage ID
    /// - Returns: Human-readable usage name, or hex string for unknown usages
    func lookupUsageName(page: UInt16, usage: UInt16) -> String
}

/// Implementation of Usage Table lookup based on HID Usage Tables 1.3
public struct UsageTableLookup: UsageTableLookupProtocol, Sendable {

    public init() {}

    // MARK: - UsageTableLookupProtocol

    public func lookupPageName(page: UInt16) -> String {
        if let name = usagePageNames[page] {
            return name
        }
        return String(format: "0x%04X", page)
    }

    public func lookupUsageName(page: UInt16, usage: UInt16) -> String {
        // Special handling for Button page (0x09)
        if page == 0x09 {
            if usage == 0 {
                return "No Button Pressed"
            }
            return "Button \(usage)"
        }

        // Look up in page-specific usage tables
        if let pageUsages = usageTables[page], let name = pageUsages[usage] {
            return name
        }

        return String(format: "0x%04X", usage)
    }

    // MARK: - Usage Page Names (HID Usage Tables 1.3)

    private let usagePageNames: [UInt16: String] = [
        0x00: "Undefined",
        0x01: "Generic Desktop Page",
        0x02: "Simulation Controls",
        0x03: "VR Controls",
        0x04: "Sport Controls",
        0x05: "Game Controls",
        0x06: "Generic Device Controls",
        0x07: "Keyboard/Keypad",
        0x08: "LED",
        0x09: "Button",
        0x0A: "Ordinal",
        0x0B: "Telephony Device",
        0x0C: "Consumer",
        0x0D: "Digitizers",
        0x0E: "Haptics",
        0x0F: "Physical Input Device",
        0x10: "Unicode",
        0x12: "Eye and Head Trackers",
        0x14: "Auxiliary Display",
        0x20: "Sensors",
        0x40: "Medical Instrument",
        0x41: "Braille Display",
        0x59: "Lighting And Illumination",
        0x80: "Monitor",
        0x81: "Monitor Enumerated",
        0x82: "VESA Virtual Controls",
        0x84: "Power",
        0x85: "Battery System",
        0x8C: "Barcode Scanner",
        0x8D: "Scales",
        0x8E: "Magnetic Stripe Reader",
        0x90: "Camera Control",
        0x91: "Arcade",
        0x92: "Gaming Device",
        0xF1D0: "FIDO Alliance",
    ]

    // MARK: - Usage Tables by Page

    private let usageTables: [UInt16: [UInt16: String]] = [
        // Generic Desktop Page (0x01)
        0x01: [
            0x00: "Undefined",
            0x01: "Pointer",
            0x02: "Mouse",
            0x04: "Joystick",
            0x05: "Game Pad",
            0x06: "Keyboard",
            0x07: "Keypad",
            0x08: "Multi-axis Controller",
            0x09: "Tablet PC System Controls",
            0x0A: "Water Cooling Device",
            0x0B: "Computer Chassis Device",
            0x0C: "Wireless Radio Controls",
            0x0D: "Portable Device Control",
            0x0E: "System Multi-Axis Controller",
            0x0F: "Spatial Controller",
            0x10: "Assistive Control",
            0x11: "Device Dock",
            0x12: "Dockable Device",
            0x13: "Call State Management Control",
            0x30: "X",
            0x31: "Y",
            0x32: "Z",
            0x33: "Rx",
            0x34: "Ry",
            0x35: "Rz",
            0x36: "Slider",
            0x37: "Dial",
            0x38: "Wheel",
            0x39: "Hat Switch",
            0x3A: "Counted Buffer",
            0x3B: "Byte Count",
            0x3C: "Motion Wakeup",
            0x3D: "Start",
            0x3E: "Select",
            0x40: "Vx",
            0x41: "Vy",
            0x42: "Vz",
            0x43: "Vbrx",
            0x44: "Vbry",
            0x45: "Vbrz",
            0x46: "Vno",
            0x47: "Feature Notification",
            0x48: "Resolution Multiplier",
            0x49: "Qx",
            0x4A: "Qy",
            0x4B: "Qz",
            0x4C: "Qw",
            0x80: "System Control",
            0x81: "System Power Down",
            0x82: "System Sleep",
            0x83: "System Wake Up",
            0x84: "System Context Menu",
            0x85: "System Main Menu",
            0x86: "System App Menu",
            0x87: "System Menu Help",
            0x88: "System Menu Exit",
            0x89: "System Menu Select",
            0x8A: "System Menu Right",
            0x8B: "System Menu Left",
            0x8C: "System Menu Up",
            0x8D: "System Menu Down",
            0x8E: "System Cold Restart",
            0x8F: "System Warm Restart",
            0x90: "D-pad Up",
            0x91: "D-pad Down",
            0x92: "D-pad Right",
            0x93: "D-pad Left",
            0x94: "Index Trigger",
            0x95: "Palm Trigger",
            0x96: "Thumbstick",
            0x97: "System Function Shift",
            0x98: "System Function Shift Lock",
            0x99: "System Function Shift Lock Indicator",
            0x9A: "System Dismiss Notification",
            0x9B: "System Do Not Disturb",
            0xA0: "System Dock",
            0xA1: "System Undock",
            0xA2: "System Setup",
            0xA3: "System Break",
            0xA4: "System Debugger Break",
            0xA5: "Application Break",
            0xA6: "Application Debugger Break",
            0xA7: "System Speaker Mute",
            0xA8: "System Hibernate",
            0xB0: "System Display Invert",
            0xB1: "System Display Internal",
            0xB2: "System Display External",
            0xB3: "System Display Both",
            0xB4: "System Display Dual",
            0xB5: "System Display Toggle Int/Ext",
            0xB6: "System Display Swap Primary/Secondary",
            0xB7: "System Display LCD Autoscale",
        ],

        // Consumer Page (0x0C)
        0x0C: [
            0x00: "Unassigned",
            0x01: "Consumer Control",
            0x02: "Numeric Key Pad",
            0x03: "Programmable Buttons",
            0x04: "Microphone",
            0x05: "Headphone",
            0x06: "Graphic Equalizer",
            0x20: "+10",
            0x21: "+100",
            0x22: "AM/PM",
            0x30: "Power",
            0x31: "Reset",
            0x32: "Sleep",
            0x33: "Sleep After",
            0x34: "Sleep Mode",
            0x35: "Illumination",
            0x36: "Function Buttons",
            0x40: "Menu",
            0x41: "Menu Pick",
            0x42: "Menu Up",
            0x43: "Menu Down",
            0x44: "Menu Left",
            0x45: "Menu Right",
            0x46: "Menu Escape",
            0x47: "Menu Value Increase",
            0x48: "Menu Value Decrease",
            0x60: "Data On Screen",
            0x61: "Closed Caption",
            0x62: "Closed Caption Select",
            0x63: "VCR/TV",
            0x64: "Broadcast Mode",
            0x65: "Snapshot",
            0x66: "Still",
            0x80: "Selection",
            0x81: "Assign Selection",
            0x82: "Mode Step",
            0x83: "Recall Last",
            0x84: "Enter Channel",
            0x85: "Order Movie",
            0x86: "Channel",
            0x87: "Media Selection",
            0x88: "Media Select Computer",
            0x89: "Media Select TV",
            0x8A: "Media Select WWW",
            0x8B: "Media Select DVD",
            0x8C: "Media Select Telephone",
            0x8D: "Media Select Program Guide",
            0x8E: "Media Select Video Phone",
            0x8F: "Media Select Games",
            0x90: "Media Select Messages",
            0x91: "Media Select CD",
            0x92: "Media Select VCR",
            0x93: "Media Select Tuner",
            0x94: "Quit",
            0x95: "Help",
            0x96: "Media Select Tape",
            0x97: "Media Select Cable",
            0x98: "Media Select Satellite",
            0x99: "Media Select Security",
            0x9A: "Media Select Home",
            0x9B: "Media Select Call",
            0x9C: "Channel Increment",
            0x9D: "Channel Decrement",
            0x9E: "Media Select SAP",
            0xA0: "VCR Plus",
            0xA1: "Once",
            0xA2: "Daily",
            0xA3: "Weekly",
            0xA4: "Monthly",
            0xB0: "Play",
            0xB1: "Pause",
            0xB2: "Record",
            0xB3: "Fast Forward",
            0xB4: "Rewind",
            0xB5: "Scan Next Track",
            0xB6: "Scan Previous Track",
            0xB7: "Stop",
            0xB8: "Eject",
            0xB9: "Random Play",
            0xBA: "Select Disc",
            0xBB: "Enter Disc",
            0xBC: "Repeat",
            0xBD: "Tracking",
            0xBE: "Track Normal",
            0xBF: "Slow Tracking",
            0xC0: "Frame Forward",
            0xC1: "Frame Back",
            0xC2: "Mark",
            0xC3: "Clear Mark",
            0xC4: "Repeat From Mark",
            0xC5: "Return To Mark",
            0xC6: "Search Mark Forward",
            0xC7: "Search Mark Backwards",
            0xC8: "Counter Reset",
            0xC9: "Show Counter",
            0xCA: "Tracking Increment",
            0xCB: "Tracking Decrement",
            0xCC: "Stop/Eject",
            0xCD: "Play/Pause",
            0xCE: "Play/Skip",
            0xE0: "Volume",
            0xE1: "Balance",
            0xE2: "Mute",
            0xE3: "Bass",
            0xE4: "Treble",
            0xE5: "Bass Boost",
            0xE6: "Surround Mode",
            0xE7: "Loudness",
            0xE8: "MPX",
            0xE9: "Volume Increment",
            0xEA: "Volume Decrement",
        ],

        // Keyboard/Keypad Page (0x07) - Common keys
        0x07: [
            0x00: "Reserved (no event)",
            0x01: "Keyboard ErrorRollOver",
            0x02: "Keyboard POSTFail",
            0x03: "Keyboard ErrorUndefined",
            0x04: "Keyboard a and A",
            0x05: "Keyboard b and B",
            0x06: "Keyboard c and C",
            0x07: "Keyboard d and D",
            0x08: "Keyboard e and E",
            0x09: "Keyboard f and F",
            0x0A: "Keyboard g and G",
            0x0B: "Keyboard h and H",
            0x0C: "Keyboard i and I",
            0x0D: "Keyboard j and J",
            0x0E: "Keyboard k and K",
            0x0F: "Keyboard l and L",
            0x10: "Keyboard m and M",
            0x11: "Keyboard n and N",
            0x12: "Keyboard o and O",
            0x13: "Keyboard p and P",
            0x14: "Keyboard q and Q",
            0x15: "Keyboard r and R",
            0x16: "Keyboard s and S",
            0x17: "Keyboard t and T",
            0x18: "Keyboard u and U",
            0x19: "Keyboard v and V",
            0x1A: "Keyboard w and W",
            0x1B: "Keyboard x and X",
            0x1C: "Keyboard y and Y",
            0x1D: "Keyboard z and Z",
            0x1E: "Keyboard 1 and !",
            0x1F: "Keyboard 2 and @",
            0x20: "Keyboard 3 and #",
            0x21: "Keyboard 4 and $",
            0x22: "Keyboard 5 and %",
            0x23: "Keyboard 6 and ^",
            0x24: "Keyboard 7 and &",
            0x25: "Keyboard 8 and *",
            0x26: "Keyboard 9 and (",
            0x27: "Keyboard 0 and )",
            0x28: "Keyboard Return (ENTER)",
            0x29: "Keyboard ESCAPE",
            0x2A: "Keyboard DELETE (Backspace)",
            0x2B: "Keyboard Tab",
            0x2C: "Keyboard Spacebar",
            0x2D: "Keyboard - and _",
            0x2E: "Keyboard = and +",
            0x2F: "Keyboard [ and {",
            0x30: "Keyboard ] and }",
            0x31: "Keyboard \\ and |",
            0x33: "Keyboard ; and :",
            0x34: "Keyboard ' and \"",
            0x35: "Keyboard ` and ~",
            0x36: "Keyboard , and <",
            0x37: "Keyboard . and >",
            0x38: "Keyboard / and ?",
            0x39: "Keyboard Caps Lock",
            0x3A: "Keyboard F1",
            0x3B: "Keyboard F2",
            0x3C: "Keyboard F3",
            0x3D: "Keyboard F4",
            0x3E: "Keyboard F5",
            0x3F: "Keyboard F6",
            0x40: "Keyboard F7",
            0x41: "Keyboard F8",
            0x42: "Keyboard F9",
            0x43: "Keyboard F10",
            0x44: "Keyboard F11",
            0x45: "Keyboard F12",
            0x46: "Keyboard PrintScreen",
            0x47: "Keyboard Scroll Lock",
            0x48: "Keyboard Pause",
            0x49: "Keyboard Insert",
            0x4A: "Keyboard Home",
            0x4B: "Keyboard PageUp",
            0x4C: "Keyboard Delete Forward",
            0x4D: "Keyboard End",
            0x4E: "Keyboard PageDown",
            0x4F: "Keyboard RightArrow",
            0x50: "Keyboard LeftArrow",
            0x51: "Keyboard DownArrow",
            0x52: "Keyboard UpArrow",
            0xE0: "Keyboard LeftControl",
            0xE1: "Keyboard LeftShift",
            0xE2: "Keyboard LeftAlt",
            0xE3: "Keyboard Left GUI",
            0xE4: "Keyboard RightControl",
            0xE5: "Keyboard RightShift",
            0xE6: "Keyboard RightAlt",
            0xE7: "Keyboard Right GUI",
        ],

        // LED Page (0x08) - Common LEDs
        0x08: [
            0x00: "Undefined",
            0x01: "Num Lock",
            0x02: "Caps Lock",
            0x03: "Scroll Lock",
            0x04: "Compose",
            0x05: "Kana",
            0x06: "Power",
            0x07: "Shift",
            0x08: "Do Not Disturb",
            0x09: "Mute",
            0x0A: "Tone Enable",
            0x0B: "High Cut Filter",
            0x0C: "Low Cut Filter",
            0x0D: "Equalizer Enable",
            0x0E: "Sound Field On",
            0x0F: "Surround On",
            0x10: "Repeat",
            0x11: "Stereo",
            0x12: "Sampling Rate Detect",
            0x13: "Spinning",
            0x14: "CAV",
            0x15: "CLV",
            0x16: "Recording Format Detect",
            0x17: "Off-Hook",
            0x18: "Ring",
            0x19: "Message Waiting",
            0x1A: "Data Mode",
            0x1B: "Battery Operation",
            0x1C: "Battery OK",
            0x1D: "Battery Low",
            0x1E: "Speaker",
            0x1F: "Head Set",
            0x20: "Hold",
            0x21: "Microphone",
            0x22: "Coverage",
            0x23: "Night Mode",
            0x24: "Send Calls",
            0x25: "Call Pickup",
            0x26: "Conference",
            0x27: "Stand-by",
            0x28: "Camera On",
            0x29: "Camera Off",
            0x2A: "On-Line",
            0x2B: "Off-Line",
            0x2C: "Busy",
            0x2D: "Ready",
            0x2E: "Paper-Out",
            0x2F: "Paper-Jam",
            0x30: "Remote",
            0x31: "Forward",
            0x32: "Reverse",
            0x33: "Stop",
            0x34: "Rewind",
            0x35: "Fast Forward",
            0x36: "Play",
            0x37: "Pause",
            0x38: "Record",
            0x39: "Error",
        ],

        // Digitizers Page (0x0D) - Common usages
        0x0D: [
            0x00: "Undefined",
            0x01: "Digitizer",
            0x02: "Pen",
            0x03: "Light Pen",
            0x04: "Touch Screen",
            0x05: "Touch Pad",
            0x06: "Whiteboard",
            0x07: "Coordinate Measuring Machine",
            0x08: "3D Digitizer",
            0x09: "Stereo Plotter",
            0x0A: "Articulated Arm",
            0x0B: "Armature",
            0x0C: "Multiple Point Digitizer",
            0x0D: "Free Space Wand",
            0x0E: "Device Configuration",
            0x0F: "Capacitive Heat Map Digitizer",
            0x20: "Stylus",
            0x21: "Puck",
            0x22: "Finger",
            0x23: "Device settings",
            0x24: "Character Gesture",
            0x30: "Tip Pressure",
            0x31: "Barrel Pressure",
            0x32: "In Range",
            0x33: "Touch",
            0x34: "Untouch",
            0x35: "Tap",
            0x36: "Quality",
            0x37: "Data Valid",
            0x38: "Transducer Index",
            0x39: "Tablet Function Keys",
            0x3A: "Program Change Keys",
            0x3B: "Battery Strength",
            0x3C: "Invert",
            0x3D: "X Tilt",
            0x3E: "Y Tilt",
            0x3F: "Azimuth",
            0x40: "Altitude",
            0x41: "Twist",
            0x42: "Tip Switch",
            0x43: "Secondary Tip Switch",
            0x44: "Barrel Switch",
            0x45: "Eraser",
            0x46: "Tablet Pick",
            0x47: "Touch Valid",
            0x48: "Width",
            0x49: "Height",
            0x51: "Contact Identifier",
            0x52: "Device Mode",
            0x53: "Device Identifier",
            0x54: "Contact Count",
            0x55: "Contact Count Maximum",
            0x56: "Scan Time",
            0x57: "Surface Switch",
            0x58: "Button Switch",
            0x59: "Pad Type",
            0x5A: "Secondary Barrel Switch",
            0x5B: "Transducer Serial Number",
            0x5C: "Preferred Color",
            0x5D: "Preferred Color is Locked",
            0x5E: "Preferred Line Width",
            0x5F: "Preferred Line Width is Locked",
        ],
    ]
}
